### ISSUE TITLE
encode special characters in symbol names for doc pages

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cljs.info#54]
clojuredocs encodes symbols like this for their URLs, like `coll_q` instead of `coll?`: [source](https://github.com/zk/clojuredocs/blob/813caf018bc2f0681553581761c222f3f9b78d7f/src/cljx/clojuredocs/util.cljx#L58-L66)

```clj
(defn cd-encode [s]
  (when s
    (cond
      (= "." s) "_."
      (= ".." s) "_.."
      :else (-> s
                (str/replace #"/" "_fs")
                (str/replace #"\\" "_bs")
                (str/replace #"\?" "_q")))))
```

**Comment by oakmac** [comment]
https://github.com/oakmac/cljs.info/blob/master/cljs-server/cljsinfo_server/core.cljs#L34-L44
