### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by shaunlebron** [oakmac/cljs.info#7]
> I think that ClojureScript should have a separate visual identity from Clojure proper, though it should pay homeage to the Clojure identity.
> -- from [ClojureScript's Launch Plan](https://github.com/clojure/clojurescript/wiki/Launch-Plan):

Just haphazardly getting this weird idea out of my head to combine the Clojure and JS logos.

<img src="https://cloud.githubusercontent.com/assets/116838/4553824/68e47756-4ea1-11e4-840d-c71bab5df358.png" width="200px"> <img src="https://cloud.githubusercontent.com/assets/116838/4553833/a759d6e8-4ea1-11e4-91ce-e63018262c33.png" width="200px"> <img src="https://cloud.githubusercontent.com/assets/116838/4553843/e2ad9310-4ea1-11e4-9ea1-09d6668d8f4d.png" width="200px">

- The lambda seems compulsory for a clojurescript logo, and it seems to beg to share the curve on that J somehow.
- The form might be confusing (i.e. "what is AJS?").
- Maybe you can imagine the lambda composed of a rotated C and L, to complete "CLJS", in an illegible graffiti sort of way.

**Comment by oakmac** [comment]
![cljs-logo](https://cloud.githubusercontent.com/assets/98485/5996836/9ad8e5d6-aa76-11e4-9966-3c61eb582ba7.png)
